# 生成 runtime/luts 预设 .cube（color_filter 调色手法用；17³ 网格）
# 用法：python scripts/make_luts.py [输出目录=runtime/luts]
# 预设意图与 color_filter._PRESET_FALLBACK 对齐：
#   warm 暖调（红进蓝退）/ cool 冷调（蓝进红退）/ film 胶片（降饱和+提对比）
# 产物为纯文本 .cube，可进版本库；重新生成直接覆盖运行。
from __future__ import annotations

import sys
from pathlib import Path

_SIZE = 17          # 每轴格点数；轻度全局调色 17 足够平滑
_STEP = 1.0 / (_SIZE - 1)


def _clamp01(v: float) -> float:
    return min(max(v, 0.0), 1.0)


def _warm(r: float, g: float, b: float) -> tuple[float, float, float]:
    return _clamp01(r * 1.10 + 0.02), g, _clamp01(b * 0.90)


def _cool(r: float, g: float, b: float) -> tuple[float, float, float]:
    return _clamp01(r * 0.90), g, _clamp01(b * 1.10 + 0.02)


def _film(r: float, g: float, b: float) -> tuple[float, float, float]:
    # 降饱和 0.9（Rec.709 亮度）→ S 形对比 1.08（0.5 为轴）
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b
    r, g, b = (luma + (c - luma) * 0.9 for c in (r, g, b))
    return tuple(_clamp01((c - 0.5) * 1.08 + 0.5) for c in (r, g, b))  # type: ignore[return-value]


_PRESETS: dict[str, object] = {
    "warm": _warm,
    "cool": _cool,
    "film": _film,
}


def write_cube(dest: Path, fn) -> None:
    lines = [
        f'# "{dest.stem}" tonal preset for YuChongGou color_filter',
        "# Generated by scripts/make_luts.py; Editable via that script.",
        f"LUT_3D_SIZE {_SIZE}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",     # 表体前保留空行，兼容部分解析器
    ]
    # .cube 约定：红分量变化最快，蓝最慢
    for bi in range(_SIZE):
        for gi in range(_SIZE):
            for ri in range(_SIZE):
                r, g, b = fn(ri * _STEP, gi * _STEP, bi * _STEP)
                lines.append(f"{r:.6f} {g:.6f} {b:.6f}")
    dest.write_text("\n".join(lines) + "\n", encoding="ascii")


def main(out_dir: str) -> int:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for name, fn in _PRESETS.items():
        dest = out / f"{name}.cube"
        write_cube(dest, fn)
        print(f"generated: {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "runtime/luts"))
